config/routes.rb
Rails.application.routes.draw do
  get 'search/show'
  get 'starships/show'
  get 'planets/show'
  get 'character/index'
  root 'movies#index' 

  get '/movies/:id', to: 'movies#show', as: :movie

  #get '/character/:url', to: 'character#index', as: :character
  get '/character/:url', to: 'character#show', as: :character

  get '/planets/:id', to: 'planets#show', as: :planets

  get '/starships/:id', to: 'starships#show', as: :starships

  get '/search/:id', to: 'search#show', as: :search

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/character_controller.rb
class CharacterController < ApplicationController

  def show
    id = params[:url]
    body = '{ person(id: "%s"){ name birthYear eyeColor gender hairColor height mass skinColor homeworld { id name } filmConnection{ films { title id } } starshipConnection{ starships{ name id } } } }' %id
    query = {'query': body }
    @character = HTTParty.get('https://swapi-graphql-integracion-t3.herokuapp.com/', :body => query)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    query = {'query': '{allFilms { edges { node { id title releaseDate director producers episodeID } } } }'}
    @movies = HTTParty.get('https://swapi-graphql-integracion-t3.herokuapp.com/', :body => query)
  end


  def show
    id = params[:id]
    body = '{ film ( id: "%s" ) { title episodeID openingCrawl director producers releaseDate starshipConnection { starships { name id } } planetConnection { planets { name id } } characterConnection { characters { name id } } } }' %id
    query = {'query': body }
    @movie = HTTParty.get('https://swapi-graphql-integracion-t3.herokuapp.com/', :body => query)

  end


end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  def show
    id = params[:id]
    body = '{planet(id: "%s"){ name diameter rotationPeriod orbitalPeriod gravity population climates terrains surfaceWater residentConnection{ residents{ name id } } filmConnection{ films{ title id } }}}' %id
    query = {'query': body }
    puts(body)
    @planet = HTTParty.get('https://swapi-graphql-integracion-t3.herokuapp.com/', :body => query)
    puts(@planet)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def show
    if params[:search]
      @param = params[:search]
      #@people = HTTParty.get('https://swapi.co/api/people/?search=' + param)
      #@planets = HTTParty.get('https://swapi.co/api/planets/?search=' + param)
      #@starships = HTTParty.get('https://swapi.co/api/starships/?search=' + param)
      #@movies = HTTParty.get('https://swapi.co/api/films/?search=' + param)
    end
  end
end

app/controllers/starships_controller.rb
class StarshipsController < ApplicationController
  def show
    id = params[:id]
    body = '{starship(id: "%s") { name model starshipClass manufacturers costInCredits length crew passengers maxAtmospheringSpeed hyperdriveRating MGLT cargoCapacity consumables pilotConnection{ pilots{ name id } } filmConnection{ films{ title id } } }}' %id
    puts(body)
    query = {'query': body}
    @starship = HTTParty.get('https://swapi-graphql-integracion-t3.herokuapp.com/', :body => query)
    puts(@starship)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/character_helper.rb
module CharacterHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/planets_helper.rb
module PlanetsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/starships_helper.rb
module StarshipsHelper
end

app/views/character/show.html.erb
<center>
<h1><%= @character['data']['person']['name'] %></h1>


<table border="1">
    <thead>
        <tr>
            <th>Birth year</th>
            <th>Eye color</th>
            <th>Gender</th>
            <th>Hair color</th>
            <th>Height</th>
            <th>Mass</th>
            <th>Skin color</th>
            <th>Homeworld</th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td><%= @character['data']['person']['birthYear'] %></td>
            <td><%= @character['data']['person']['eyeColor'] %></td>
            <td><%= @character['data']['person']['gender'] %></td>
            <td><%= @character['data']['person']['hairColor'] %></td>
            <td><%= @character['data']['person']['height'] %></td>
            <td><%= @character['data']['person']['mass'] %></td>
            <td><%= @character['data']['person']['skinColor'] %></td>
            <td><%= link_to @character['data']['person']['homeworld']['name'], planets_path(@character['data']['person']['homeworld']['id']) %></td>
        </tr>
    </tbody>
</table> 

<table border="1">
  <thead>
      <tr>
        <th>Films</th>
        <th>Starships</th>
      </tr>
  </thead>

  <tbody>
      <tr>
        <td><% @character['data']['person']['filmConnection']['films'].each do |m|%>
            <li><%= link_to m['title'], movie_path(m['id']) %></li>
          <% end %></td>
        <td><% @character['data']['person']['starshipConnection']['starships'].each do |s|%>
            <li><%= link_to s['name'], starships_path(s['id']) %></li>
            <% end %></td>
      </tr>
  </tbody>
</table> 
</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>T1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :episode_id %>
    <%= form.number_field :episode_id %>
  </div>

  <div class="field">
    <%= form.label :release_date %>
    <%= form.date_select :release_date %>
  </div>

  <div class="field">
    <%= form.label :director %>
    <%= form.text_field :director %>
  </div>

  <div class="field">
    <%= form.label :producer %>
    <%= form.text_field :producer %>
  </div>

  <div class="field">
    <%= form.label :opening_crwl %>
    <%= form.text_field :opening_crwl %>
  </div>

  <div class="field">
    <%= form.label :species %>
    <%= form.text_field :species %>
  </div>

  <div class="field">
    <%= form.label :starships %>
    <%= form.text_field :starships %>
  </div>

  <div class="field">
    <%= form.label :vehicles %>
    <%= form.text_field :vehicles %>
  </div>

  <div class="field">
    <%= form.label :characters %>
    <%= form.text_field :characters %>
  </div>

  <div class="field">
    <%= form.label :planets %>
    <%= form.text_field :planets %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :created %>
    <%= form.text_field :created %>
  </div>

  <div class="field">
    <%= form.label :edited %>
    <%= form.text_field :edited %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<center>
<h1>Star wars</h1>

<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Year</th>
            <th>Director</th>
            <th>Producer</th>
            <th>Episode</th>
            <th>More</th>
        </tr>
    </thead>

    <tbody>
        <% @movies['data']['allFilms']['edges'].each do |movie|%>
        <tr>
            <td><%= movie['node']['title'] %></td>
            <td><%= movie['node']['releaseDate'] %></td>
            <td><%= movie['node']['director'] %></td>
            <td><%= movie['node']['producers'] %></td>
            <td><%= movie['node']['episodeID'] %></td>
            <td><%= link_to 'More info', movie_path(movie['node']['id']) %></td>
        </tr>
        <% end %>
    </tbody>
</table> 
</center>

app/views/movies/show.html.erb
<center>
<h1><%= @movie['data']['film']['title'] %></h1>

<table border="1">
    <thead>
        <tr>
            <th>Title</th>
            <th>Year</th>
            <th>Director</th>
            <th>Producer</th>
            <th>Episode</th>
            <th>Characters</th>
            <th>Planets</th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td><%= @movie['data']['film']['title'] %></td>
            <td><%= @movie['data']['film']['releaseDate'] %></td>
            <td><%= @movie['data']['film']['director'] %></td>
            <td><%= @movie['data']['film']['producers'] %></td>
            <td><%= @movie['data']['film']['episodeID'] %></td>
            <td><% @movie['data']['film']['characterConnection']['characters'].each do |c|%>
              <li><%= link_to c['name'], character_path(c['id']) %></li>
              <% end %></td>
            <td><% @movie['data']['film']['planetConnection']['planets'].each do |p|%>
              <li><%= link_to p['name'], planets_path(p['id']) %></li>
              <% end %></td>
        </tr>
    </tbody>
</table> 

<table border="1">
  <thead>
      <tr>
        <th>Starships</th>
        <th>Opening crawl</th>
      </tr>
  </thead>

  <tbody>
      <tr>
        <td><% @movie['data']['film']['starshipConnection']['starships'].each do |s|%>
        <li><%= link_to s['name'], starships_path(s['id']) %></li>
          <% end %></td>
        <td width="500"><%= @movie['data']['film']['openingCrawl'] %></td>
      </tr>
  </tbody>
</table> 
</center>

app/views/planets/show.html.erb
<center>
    <h1><%= @planet['data']['planet']['name'] %></h1>
    
    <table border="1"> 
        <thead>
            <tr>
                <th>Name</th>
                <th>Diameter</th>
                <th>Rotation period</th>
                <th>Orbital period</th>
                <th>Gravity</th>
                <th>Population</th>
                <th>Climate</th>
                <th>Terrain</th>
                <th>Surface water</th>
            </tr>
        </thead>
    
        <tbody>
            <tr>
                <td><%= @planet['data']['planet']['name'] %></td>
                <td><%= @planet['data']['planet']['diameter'] %></td>
                <td><%= @planet['data']['planet']['rotationPeriod'] %></td>
                <td><%= @planet['data']['planet']['orbitalPeriod'] %></td>
                <td><%= @planet['data']['planet']['gravity'] %></td>
                <td><%= @planet['data']['planet']['population'] %></td>
                <td><%= @planet['data']['planet']['climates'] %></td>
                <td><%= @planet['data']['planet']['terrains'] %></td>
                <td><%= @planet['data']['planet']['surfaceWater'] %></td>
            </tr>
        </tbody>
    </table> 
    
    <table border="1">
      <thead>
          <tr>
            <th>Films</th>
            <th>Residents</th>
          </tr>
      </thead>
    
      <tbody>
          <tr>
            <td><% @planet['data']['planet']['filmConnection']['films'].each do |m|%>
              <li><%= link_to m['title'], movie_path(m['id']) %> </li>
              <% end %></td>
            <td><% @planet['data']['planet']['residentConnection']['residents'].each do |p|%>
                <li> <%= link_to p['name'], character_path(p['id']) %> </li>
                <% end %></td>
          </tr>
      </tbody>
    </table> 
    </center>

app/views/search/show.html.erb
<% @param %>
<% planets = HTTParty.get('https://swapi.co/api/planets/?search=' + @param) %>
<% peoples = HTTParty.get('https://swapi.co/api/people/?search=' + @param) %>
<% starships = HTTParty.get('https://swapi.co/api/starships/?search=' + @param) %>
<% films = HTTParty.get('https://swapi.co/api/films/?search=' + @param) %>

<%= form_tag(search_path(:search), method: :get) do %>
<%= text_field_tag(:search, params[:search]) %>
<%= submit_tag('Search') %>
<% end %>

<center>
<h2>Your search</h2>

<table border="1">
    <thead>
        <tr>
            <th>Films</th>
            <th>People</th>
            <th>Planets</th>
            <th>Starships</th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td><% films['results'].each do |film|%>
                <% b = film['url'] %>
                <% b = b.split('/') %>
                <li><%= link_to film['title'], movie_path(b[-1]) %></li>
                <% end %></td>
            <td><% peoples['results'].each do |p|%>
                <% b = p['url'] %>
                <% b = b.split('/') %>
                <li><%= link_to p['name'], character_path(b[-1]) %></li>
                <% end %></td>
            <td><% planets['results'].each do |pl|%>
                <% b = pl['url'] %>
                <% b = b.split('/') %>
                <li><%= link_to pl['name'], planets_path(b[-1]) %></li>
                <% end %></td>
            <td><% starships['results'].each do |s|%>
                <% b = s['url'] %>
                <% b = b.split('/') %>
                <li><%= link_to s['name'], starships_path(b[-1]) %></li>
                <% end %></td>
        </tr>
    </tbody>
</table border="1"> 
</center>

app/views/starships/show.html.erb
<center>
    <h2><%= @starship['data']['starship']['name'] %></h2>
    
    <table border="1">
        <thead>
            <tr>
                <th>Name</th>
                <th>Model</th>
                <th>Starship class</th>
                <th>Manufacturer</th>
                <th>Cost in credits</th>
                <th>Length</th>
                <th>Crew</th>
                <th>Passengers</th>
                <th>Max atmosphering spped</th>
                <th>Hyperdrive rating</th>
            </tr>
        </thead>
    
        <tbody>
            <tr>
                <td><%= @starship['data']['starship']['name'] %></td>
                <td><%= @starship['data']['starship']['model'] %></td>
                <td><%= @starship['data']['starship']['starshipClass'] %></td>
                <td><%= @starship['data']['starship']['manufacturers'] %></td>
                <td><%= @starship['data']['starship']['costInCredits'] %></td>
                <td><%= @starship['data']['starship']['length'] %></td>
                <td><%= @starship['data']['starship']['crew'] %></td>
                <td><%= @starship['data']['starship']['passengers'] %></td>
                <td><%= @starship['data']['starship']['maxStmospheringSpeed'] %></td>
                <td><%= @starship['data']['starship']['hyperdriveRating'] %></td>
            </tr>
        </tbody>
    </table> 
    
    <table border="1">
      <thead>
          <tr>
            <th>MGLT</th>
            <th>Cargo capacity</th>
            <th>Consumables</th>
            <th>Films</th>
            <th>Pilots</th>
          </tr>
      </thead>
    
      <tbody>
          <tr>
            <td><%= @starship['data']['starship']['MGLT'] %></td>
            <td><%= @starship['data']['starship']['cargoCapacity'] %></td>
            <td><%= @starship['data']['starship']['consumables'] %></td>
            <td><% @starship['data']['starship']['filmConnection']['films'].each do |m|%>
              <li><%= link_to m['title'], movie_path(m['id']) %></li>
              <% end %></td>
            <td><% @starship['data']['starship']['pilotConnection']['pilots'].each do |p|%>
                <li><%= link_to p['name'], character_path(p['id']) %></li>
                <% end %></td>
          </tr>
      </tbody>
    </table> 
    </center>